version: "3"

services:
  licensetogo-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: licensetogo-api
    volumes:
      - ${HOME}/ltg/pb_data:/app/pb_data
    ports:
      - "8090:8090"
    networks:
      - licensetogo-network

  licensetogo-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: licensetogo-web
    environment:
      - PUBLIC_API_URL=http://licensetogo-api:8090
      - ORIGIN=http://localhost:80
    ports:
      - "80:3000"
    networks:
      - licensetogo-network

networks:
  licensetogo-network:
    name: licensetogo-network
    driver: bridge
