name: Build and Push Docker Images
on:
  push:
    branches-ignore: ["**"]
    tags: ["v*"] # Trigger on version tags
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (optional)"
        required: false
        default: ""
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper versioning
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Generate version information
      - name: Generate version info
        id: version
        run: |
          # Manual version from workflow dispatch
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.version }}" != "" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          # Git tag
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          # Default case - should not happen with branches-ignore: ['**']
          else
            echo "Error: Build triggered outside of expected conditions"
            exit 1
          fi

          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Generated VERSION: ${VERSION}"

      # Build and push API image
      - name: Build and push licensetogo api
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          target: api
          tags: |
            karurosuxx/licensetogo-api:latest
            karurosuxx/licensetogo-api:${{ steps.version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Web image
      - name: Build and push licensetogo web
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          target: web
          tags: |
            karurosuxx/licensetogo-web:latest
            karurosuxx/licensetogo-web:${{ steps.version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
